### ISSUE TITLE
Module Loads but no games loading

### ISSUE THREAD

**Issue by doubled136** [buxxi/MMM-Liquipedia-Dota2#2]
Working to default instructions but the game items are not loading.

**Comment by buxxi** [comment]
Hi,

- Do you have any logs from MagicMirror about the error?
- Do you have the alert-module enabled, if so do you get any errors about it on the display?
- Does this link work for you: https://liquipedia.net/dota2/api.php?action=parse&format=json&page=Liquipedia:Upcoming_and_ongoing_matches or do you get any captcha? If you have tried to restart it too many times you may have been temporary blocked from Liquipedia until you finish that captcha.

**Comment by doubled136** [comment]
I got it to load once, near the top of an hour, but am having some interaction issues with other modules.

I'll continue to troubleshoot over the next few days and get back to you.  Thank you again!

**Comment by doubled136** [comment]
I was getting an error related to the "currentweather" module, which caused it to suspend while the Dota2 module is loaded.

**Comment by doubled136** [comment]
Here's the console info when I disable all other modules.

Initializing MagicMirror.
translator.js:137 Loading core translation file: translations/en.json
translator.js:162 Loading core translation fallback file: translations/en.json
loader.js:176 Load script: modules/MMM-Liquipedia-Dota2//MMM-Liquipedia-Dota2.js
module.js:513 Module registered: MMM-Liquipedia-Dota2
loader.js:148 Bootstrapping module: MMM-Liquipedia-Dota2
loader.js:176 Load script: vendor/node_modules/moment/min/moment-with-locales.js
loader.js:153 Scripts loaded for: MMM-Liquipedia-Dota2
loader.js:195 Load stylesheet: modules/MMM-Liquipedia-Dota2/MMM-Liquipedia-Dota2.css
loader.js:155 Styles loaded for: MMM-Liquipedia-Dota2
translator.js:108 MMM-Liquipedia-Dota2 - Load translation: translations/en.json
translator.js:110 MMM-Liquipedia-Dota2 - Load translation fallback: translations/sv.json
loader.js:157 Translations loaded for: MMM-Liquipedia-Dota2
loader.js:195 Load stylesheet: css/custom.css
(index):1 Refused to apply style from 'http://_**[redactedIPaddress]**_:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
loader.js:206 Error on loading stylesheet: css/custom.css
main.js:508 All modules started!

**Comment by buxxi** [comment]
Unfortunately that looks normal so that didn't help.

Errors is sent to the alert-module, if you enable that module too. Does it display an error on the mirror?

**Comment by doubled136** [comment]
When I ran just the Liquipedia module, alert-module notified me that it needed the Clock module.  When I enabled the clock module, no on-screen error occurred.  Both the clock and the Liquipedia modules loaded, but no games showed up.

**Comment by buxxi** [comment]
Kinda hard debugging when no errors occurs :smile: 

Some things you can try:
1. Make the MagicMirror accessible for your network and use a browser and open the developer tools (F12 in Firefox/Chrome) and navigate to it and check the console log for any errors.
2. Add a `console.log(result);` in node_helper.js line 112 just before the `return result;`
3. I took a dump of the api result and saved as a gist, set it in your config (this will only for a few days until all those matches has been played):
`
config: {
    sourceUrl: 'https://gist.githubusercontent.com/buxxi/89b53528c57e0a6e335d50a68d60d96f/raw/5e7e82bf8c3b0edc8446d8b4c84e00a12b3d6966/api_example.json'
}
`

**Comment by doubled136** [comment]
Did some further modification and there were issues with initial load of my mirror.  The issue can be closed at present.

**Comment by doubled136** [comment]
Thank you again for your efforts.
