### ISSUE TITLE
Games are duplicated if both teams are in "requiredTeams" array

### ISSUE THREAD

**Issue by Feedy88** [buxxi/MMM-Liquipedia-Dota2#3]
When both teams who play each other are in the "requiredTeams" array, their game will be shown twice on the mirror.

**Comment by buxxi** [comment]
It had nothing to do with the requiredTeams-array, it just made it more visible when more matches were filtered.

Liquipedia had changed their page to include filters for "Show featured matches" which included a hidden table of duplicates for all those matches.

It should be fixed now.
